name = "plantuml_parser"
description = "PlantUML parser producing a language-neutral UML model"
version = "0.1.0-dev"
licenses = "BSD-3-Clause"
authors = ["Joe Beazelman"]
maintainers = ["Joe Beazelman <joe@example.com>"]
maintainers-logins = ["Joebeazelman"]
website = "https://github.com/Joebeazelman/plantuml_parser"
tags = ["plantuml", "uml", "parser"]

[[depends-on]]
uml_model = "*"

[[pins]]
uml_model = { path='../uml_model' }
