/* Configuration for plantuml_parser generated by Alire */
#ifndef PLANTUML_PARSER_CONFIG_H
#define PLANTUML_PARSER_CONFIG_H

#define CRATE_VERSION "0.1.0"
#define CRATE_NAME "plantuml_parser"

#define ALIRE_HOST_OS "macos"

#define ALIRE_HOST_ARCH "aarch64"

#define ALIRE_HOST_DISTRO "homebrew"

#define BUILD_PROFILE_RELEASE 1
#define BUILD_PROFILE_VALIDATION 2
#define BUILD_PROFILE_DEVELOPMENT 3

#define BUILD_PROFILE  1

#endif
